{{- if .Values.backendConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendConfig.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  config.json: |
{{ .Values.backendConfig.configJson | indent 4 }}
{{- end }}