{{- if .Values.pdfDbMigration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pdfDbMigration.configMapName }}
  namespace: {{ .Values.global.namespace }}
data:
  {{ .Values.pdfDbMigration.fileName }}: |
{{ .Files.Get "migrations/pdf/schema.sql" | indent 4 }}
{{- end }}